### ISSUE TITLE
Плагин не ставится из репозитория в Kodi 17

### ISSUE THREAD

**Issue by gl-sergei** [ufian/soap4me-repo#2]
Скачал репозиторий отсюда https://soap4.me/assets/plugins/repository.soap4me.db-1.0.0.zip
Когда пытаюсь поставить плагин из репозитория, ничего не выходит. Вот что в `kodi.log`:

```
tail ~/Library/Logs/kodi.log
16:04:38 T:123145319092224  NOTICE: ES: Starting UDP Event server on port 9777
16:04:38 T:123145319092224  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
16:04:38 T:123145309892608   ERROR: GetDirectory - Error getting -
16:04:38 T:123145314799616   ERROR: GetDirectory - Error getting pvr://channels/tv/All channels/
16:04:38 T:123145309892608   ERROR: GetDirectory - Error getting pvr://channels/radio/All channels/
16:05:08 T:123145314799616   ERROR: ContextMenuManager: failed to load addons.
16:05:14 T:140735144071168   ERROR: CCurlFile::Open failed with code 404 for https://github.com/ufian/soap4me-repo/raw/master/plugin.video.soap4.me/plugin.video.soap4.me-1.0.8.zip.md5
16:05:14 T:140735144071168   ERROR: Open - failed to open source <https://github.com/ufian/soap4me-repo/raw/master/plugin.video.soap4.me/plugin.video.soap4.me-1.0.8.zip.md5>
16:05:36 T:140735144071168   ERROR: CCurlFile::Open failed with code 404 for https://github.com/ufian/soap4me-repo/raw/master/plugin.video.soap4.me/plugin.video.soap4.me-1.0.8.zip.md5
16:05:36 T:140735144071168   ERROR: Open - failed to open source <https://github.com/ufian/soap4me-repo/raw/master/plugin.video.soap4.me/plugin.video.soap4.me-1.0.8.zip.md5>
```

**Comment by ufian** [comment]
Добавил md5, надеюсь теперь работает

**Comment by DantePinky** [comment]
нет, по прежнему не работает, посмотрите?

**Comment by ufian** [comment]
Смотрел, потратил много времени, чтобы разобраться что такого делает Kodi 17, но не смог.

**Comment by eschava** [comment]
Установил новый kodi и такая же проблема
Даже непонятно как разбираться

**Comment by eschava** [comment]
Часть лога относящаяся к установке плагина

4072002429696   DEBUG: GetImageHash - unable to stat url https://github.com/ufian/soap4me-repo/raw/master/service.xbmc.soap4me/icon.png
11:42:23.576 T:18446744072346884480   DEBUG: Keyboard: scancode: 0x42, sym: 0x000d, unicode: 0x000a, modifier: 0x0
11:42:23.743 T:18446744072346884480   DEBUG: OnKey: return (0xf00d) pressed, action is Select
11:42:23.761 T:18446744072346884480   DEBUG: CAddonInstaller: installing 'service.xbmc.soap4me' version '0.1.0' from repository 'repository.soap4me.db'
11:42:23.774 T:18446744072346884480   DEBUG: CFileCache::Open - opening <ufian/soap4me-repo/raw/master/service.xbmc.soap4me/service.xbmc.soap4me-0.1.0.zip.md5> using cache
11:42:23.775 T:18446744072346884480   DEBUG: CurlFile::Open(0x9a5ac4a0) https://github.com/ufian/soap4me-repo/raw/master/service.xbmc.soap4me/service.xbmc.soap4me-0.1.0.zip.md5
11:42:25.025 T:18446744072346884480   DEBUG: CCurlFile::Open - effective URL: <https://raw.githubusercontent.com/ufian/soap4me-repo/master/service.xbmc.soap4me/service.xbmc.soap4me-0.1.0.zip.md5>
11:42:25.032 T:18446744072002430336   DEBUG: Thread FileCache start, auto delete: false
11:42:25.039 T:18446744072002430336    INFO: CFileCache::Process - Source read didn't return any data! Hit eof(?)
11:42:25.089 T:18446744072002430336   DEBUG: Thread FileCache 18446744072002430336 terminating
11:42:25.091 T:18446744072346884480   DEBUG: Keyboard: scancode: 0x42, sym: 0x000d, unicode: 0x000a, modifier: 0x0
11:42:25.110 T:18446744072346884480   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------

**Comment by eschava** [comment]
https://forum.libreelec.tv/thread-1833.html

Вот тут похожие симптомы и в итоге все решилось ручной установкой недостающих библиотек питона

**Comment by ufian** [comment]
Надо попробовать, просто раньше такого лога не было.

**Comment by eschava** [comment]
Вижу что он не только не ставится, но и не обновляется если уже установлен

**Comment by ufian** [comment]
Проблема в формате репозитория. Kodi 17 его не воспринимает и что делать с этим непонятно.

**Comment by eschava** [comment]
Кажется понял в чем дело
В конце MD5 файла должен быть перевод строки

**Comment by ufian** [comment]
Таки ты прав. Действительно помогло!
