### ISSUE TITLE
Не показывается иконка просмотренных серий

### ISSUE THREAD

**Issue by TemaGambik** [ufian/soap4me-repo#6]
После обновления kodi до 18-ой версии плагин для soap4me вместо галочек просмотренных серий стал показывать обложки сериала. Теперь невозможно понять какие серии просмотренные, а какие нет.

**Comment by darkwebdev** [comment]
Привет, спасибо за фидбек, я пока не видел 18 версии коди, воспроизведем - пофиксим.

**Comment by TemaGambik** [comment]
Забыл уточнить: это Kodi для Android TV

**Comment by darkwebdev** [comment]
я так понимаю, починили тут: https://github.com/Soap4me/Kodi/pull/12
можно закрывать
@eschava
