### ISSUE TITLE
Отображение в Kodi 18

### ISSUE THREAD

**Issue by bodva** [ufian/soap4me-repo#7]
После обновления до Kodi 18 в любом стиле отображения не понятно какая серия просмотренна, а какая нет. Все серии вместо иконки просмотра, показывают обложку сезона. Приходится вычислять наживая options на каждой, и смотря предлагает он отметить ее просмотренной или не просмотренной.

**Comment by ufian** [comment]
Спасибо за фидбек, но скорее всего это ограничение API. Если будет время, то мы посмотрим что можно сделать

**Comment by darkwebdev** [comment]
я так понимаю, починили тут: https://github.com/Soap4me/Kodi/pull/12
можно закрывать
