### ISSUE TITLE
Kodi 19.0

### ISSUE THREAD

**Issue by ConstNW** [ufian/soap4me-repo#8]
Не включается плагин на 19.0 версии, пишет о несовместимости.

**Comment by wit** [comment]
Я просто конвертнул всё это дело в python3 и нет проблем,
В Kodi 19 заменили встроенный python на 3

**Comment by darkwebdev** [comment]
@wit тебя не затруднит сделать пулл-реквест?

**Comment by ConstNW** [comment]
Да, я тоже конвертнул на дев-машине без проблем, но на тв хотелось бы получить из репы апдейт.

**Comment by wit** [comment]
@darkwebdev я смотрю прокси уже пофиксили а видео плагин нет.
Я бы сделал пул, но тут нет репы с исходниками видео плагина

**Comment by eschava** [comment]
@wit вот тут исходники видео плагина
https://github.com/Soap4me/Kodi

**Comment by darkwebdev** [comment]
Единственная проблема - мы обычно не ломаем совместимость с прежними версиями, значит надо сохранить работоспособность с питоном 2...

**Comment by eschava** [comment]
Как я понял это невозможно, так как в свойствах плагина нужно прописать `<import addon="xbmc.python" version="3.0.0"/>` что делает его несовместимым с предыдущими версиями Kodi

**Comment by wit** [comment]
Вообщем я вот с такими правками живу.
https://github.com/Soap4me/Kodi/pull/14

И второй плагин который прокси тоже правок требует, от него репа есть?

**Comment by darkwebdev** [comment]
@wit https://github.com/eschava/soap4me-proxy
но там @eschava вроде уже пофиксил

**Comment by ConstNW** [comment]
> Как я понял это невозможно, так как в свойствах плагина нужно прописать `<import addon="xbmc.python" version="3.0.0"/>` что делает его несовместимым с предыдущими версиями Kodi

@eschava по общей практике других реп эдонов под 19й коди заводят отдельный бранч

**Comment by darkwebdev** [comment]
@ConstNW пытаюсь понять, что это даст... Будет возможность поддерживать старую версию на питоне 2 или что-то еще?

**Comment by ConstNW** [comment]
@darkwebdev да, будет две ветки. одна на поддержку версии для второго питона, чтобы ничего не сломалось у тех кто не сможет апнуться до 19 коди, например, какие-то старые андроиды, которых большинство.
вторая ветка под третий питон для коди от 19й версии.

**Comment by wit** [comment]
Как вариант можно пойти по примеру кинопуб. Там просто отложили старые версии в сторону и написали требования Kodi 19+

**Comment by darkwebdev** [comment]
Мне нравится идея второй ветки. И как минимум надо зарелизить версию 1.0.20, чтобы пользователи всегда могли скачать зип со старой версией отсюда: https://github.com/Soap4me/Kodi/releases

**Comment by o10g** [comment]
> Как вариант можно пойти по примеру кинопуб. Там просто отложили старые версии в сторону и написали требования Kodi 19+

Что сделало невозможно использовать их плагин достаточно долго, пока Kodi 19 не релизнулся на android tv в маркете. У меня это случилось буквально вчера только.

**Comment by darkwebdev** [comment]
@o10g ну в нашем случае это не проблема, мы начали обновление плагина из-за обновления коди на андроид-тв. Для старого коди придется ставить старый плагин руками. Или есть более удобный процесс?

**Comment by ConstNW** [comment]
можно добавить новую версию под новым именем, например, "service.xbmc.soap4me-matrix"
они гарантированно не будут работать одновременно и не будут создавать конфликтов

**Comment by o10g** [comment]
> можно добавить новую версию под новым именем, например, "service.xbmc.soap4me-matrix"
> они гарантированно не будут работать одновременно и не будут создавать конфликтов

Хорошее решение, которое, правда, заставит переустанавливать плагин, но тут другого не дано, кажется.

**Comment by ConstNW** [comment]
примерный сценарий такой:
- на версии коди 18 у тебя работает старый плагин
- после апгрейда до 19 версии у тебя пропадает дополнение soap4me, тк не совместимо системой
- за решением ты идешь в настройки коди, в установку дополнений и видишь "поломанную" старую версию дополнения и новую
- устанавливаешь новую версию и тут случается самая большая боль - надо ввести заново логин и пароль

**Comment by o10g** [comment]
А есть понимание когда можно будет плагин поставить на 19-ю версию? Очень больно без плагина :(

**Comment by ConstNW** [comment]
@ufian В коммите https://github.com/Soap4me/Kodi-repo/commit/1df2d6af3436a7a0e56272faa49eba945bd824a1 не тот плагин обновился

**Comment by ufian** [comment]
Sorry, я коммитил-удалял, но так и не получилось правильно. Через пару часов поправлю

**Comment by ufian** [comment]
Вроде теперь правильно. Я ещё добавлю старый плагин как отдельную сущность

**Comment by ufian** [comment]
Плагин обновлен, старый плагин осьавлен для совместимости под новым id. Проверено на Kodi 17 и 19 версий
